openapi: 3.0.0
info:
  title: FHIR Server
  version: 1.0.0
  description: API for FHIR Server

servers:
  - url: http://localhost:3456
    description: Development server

paths:
  /patients:
    get:
      summary: Get all the patients from the DB
      description: Query the db for all the patients 
      responses:
        '200':
          description: Fetch all patients 
          content:
            application/json:
              example: 
                - resourceType: Patient
                  identifier:
                    system: http://example.org/patient
                    value: "12345"
                  active: true
                  name:
                    - use: official
                      family: Doe
                      given:
                        - John
                  telecom:
                    - system: phone
                      value: "555-555-5555"
                      use: home
                  gender: male
                  birthDate: "1980-01-01"
                  address:
                    - use: home
                      line:
                        - "123 Main St"
                      city: Anytown
                      state: NY
                      postalCode: "12345"
                      country: US
                  maritalStatus:
                    coding:
                      - system: http://terminology.hl7.org/CodeSystem/v3-MaritalStatus
                        code: M
                        display: Married
                  communication:
                    - language:
                        coding:
                          - system: urn:ietf:bcp:47
                            code: en-US
                            display: English
                        text: English
                      preferred: true
                  managingOrganization:
                    reference: Organization/1
                - resourceType: Patient
                  identifier:
                    system: http://example.org/patient
                    value: "67890"
                  active: true
                  name:
                    - use: official
                      family: Smith
                      given:
                        - Jane
                  telecom:
                    - system: phone
                      value: "555-123-4567"
                      use: home
                  gender: female
                  birthDate: "1975-05-20"
                  address:
                    - use: home
                      line:
                        - "456 Oak St"
                      city: Somewhere
                      state: CA
                      postalCode: "98765"
                      country: US
                  maritalStatus:
                    coding:
                      - system: http://terminology.hl7.org/CodeSystem/v3-MaritalStatus
                        code: S
                        display: Single
                  communication:
                    - language:
                        coding:
                          - system: urn:ietf:bcp:47
                            code: en-US
                            display: English
                        text: English
                      preferred: true
                  managingOrganization:
                    reference: Organization/2
        '500':
          description: Error fetching patients 
          content:
            application/json:
              example:
                error: "Internal server Error" 
  